const topMunicipalities: Array<string> = [
    'Arlington',
    'Belmont',
    'Beverly',
    'Boston',
    'Braintree',
    'Brookline',
    'Burlington',
    'Cambridge',
    'Chelsea',
    'Danvers',
    'Dedham',
    'Everett',
    'Framingham',
    'Lexington',
    'Lynn',
    'Malden',
    'Medford',
    'Melrose',
    'Middleton',
    'Natick',
    'Needham',
    'Newton',
    'Norwell',
    'Norwood',
    'Peabody',
    'Quincy',
    'Randolph',
    'Reading',
    'Revere',
    'Salem',
    'Saugus',
    'Somerville',
    'Stoneham',
    'Stoughton',
    'Swampscott',
    'Walpole',
    'Waltham',
    'Watertown',
    'Westwood',
    'Winchester',
    'Winthrop',
    'Woburn'
  ];
  
  export default topMunicipalities;
  